#!/bin/bash

log(){ >&2 echo "$@" ; }
die(){ log "$@" ; exit 1 ; }

TARGET=""
OPTIMIZE=""
SHOWEXPANSIONS=""
SHOWOPTIMIZATIONS=""

set-target(){
    if [ -z "$TARGET" ]; then
        TARGET="$2"
    else
        die target already set to "'$TARGET'", cannot set it to "'$1'"
    fi
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        "")                   die empty argument ;;
        -)                    set-target - /dev/stdin ;;
        --optimize)           OPTIMIZE=--optimize ;;
        --show-expansions)    SHOWEXPANSIONS=--show-expansions ;;
        --show-optimizations) SHOWOPTIMIZATIONS=--show-optimizations ;;
        -*)                   die unknown flag: "$1" ;;
        *)                    set-target "$1" "$1"
    esac
    shift
done

if [ -z "$TARGET" ]; then
    die error - no target specified
fi

# for some reason dwarf debugging stopped working with newer gdb

echo running ./tools/kmforth $OPTIMIZE $SHOWEXPANSIONS $SHOWOPTIMIZATIONS "$TARGET"
./tools/kmforth $OPTIMIZE $SHOWEXPANSIONS $SHOWOPTIMIZATIONS "$TARGET" > bld/SOURCE.asm || die failed to compile forth into asm
nasm -felf64 -Fdwarf -g -o bld/SOURCE.o bld/SOURCE.asm || die failed to compile asm into object library
ld -static -o bld/SOURCE.out bld/SOURCE.o || die failed to link object library into executable
cp bld/SOURCE.out a.out || die failed to copy executable into current directory
